# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Homie

# Model Form Field configuration
form: $/beeasy/downforlife/models/homie/fields.yaml

# Model Class name
modelClass: BeEasy\DownForLife\Models\Homie

# Default redirect location
defaultRedirect: beeasy/downforlife/homies

# Create page
create:
    title: Create Homie
    redirect: beeasy/downforlife/homies/update/:id
    redirectClose: beeasy/downforlife/homies

# Update page
update:
    title: Edit Homie
    redirect: beeasy/downforlife/homies
    redirectClose: beeasy/downforlife/homies

# Preview page
preview:
    title: Preview Homie
